var patri_sociocultural = {
"type": "FeatureCollection",
"name": "patri_sociocultural",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": 1, "nombre": "Camino Tocogua", "descrip": "Uno de   los muchos tributarios a la red de caminos ancestrales que conectaban las poblaciones de San Luis, La Laguna y Tobasia hacia Duitama pasando por las zonas altas. Se trata de una estrella de caminos ancestrales que evitaba las zonas inundables del valle del chicamocha. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/wgnVKpZ/camino-tocogua-tobasia.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.007181666666668, 5.825258333333334 ] } },
{ "type": "Feature", "properties": { "fid": 2, "nombre": "Zanja para lavar", "descrip": "Se trata de una zanja en la parte baja del curso de las manas que descienden del manantial en el camino al hoyo de la calera, fue realizada por los habitantes de tocogua con la finalidad de lavar allí cuando el curso del agua era constante.", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/wZtrrWC/Zanja-para-lavar.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.006396, 5.823178 ] } },
{ "type": "Feature", "properties": { "fid": 3, "nombre": "Puerta Amarilla", "descrip": "Una misteriosa puerta amarilla de adobe se yergue en el límite del camino tradicional de Tocogua hacia Argos. Fue la entrada a una antigua hacienda hoy desaparecida y evoca una época de desplazamientos ecuestres pues su dimensión se debe justamente a la necesidad de poder permitir a los jinetes ingresar sin desmontar. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/DGzQrTS/DSC06087.jpg", "https://i.ibb.co/wcW5Vsj/DSC06086.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.0055282, 5.8235712 ] } },
{ "type": "Feature", "properties": { "fid": 4, "nombre": "La Gruta", "descrip": "Se trata de un monumento religioso realizado por los vecinos de Tocogua en la tercera década del siglo pasado. Su existencia además de ser testimonio de la unión comunitaria es un vestigio de una obra cívica realizada en tiempos de confrontación política bipartidista. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/jTBJZkj/Imagen-de-Whats-App-2024-08-29-a-las-09-59-27-1038d41f.jpg", "https://i.ibb.co/4ddWKPx/Imagen-de-Whats-App-2024-08-29-a-las-09-59-26-54738ccf.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.008644100000012, 5.8205788 ] } },
{ "type": "Feature", "properties": { "fid": 5, "nombre": "Mina de piedra Laja", "descrip": "Una mina a cielo abierto, de explotación artesanal impregna la cotidianidad de Tocogua con el ruido de dragas, volquetas y maquinaria empleada en la extracción de piedra caliza. A pesar de ser una mina artesanal se trata de un inmenso agujero en la pared de la montaña que está a simple vista oculto, pero en el cual desembocan los caminos que llegan desde el pueblito boyacense. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/VC5btfg/mina-laja.jpg", "https://i.ibb.co/VVmqXFM/Piedra-laja-1.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.012035508475094, 5.820671446458066 ] } },
{ "type": "Feature", "properties": { "fid": 6, "nombre": "Mirador Arco del Cielo", "descrip": "Mirador del valle del Chicamocha al cual acceden caminantes todos los días para admirar el magnífico fenómeno de la neblina sobre la planicie inundable. Ha recibido el nombre de Mirador Arco del Cielo en los círculos de artistas y humanistas que lo frecuentan en búsqueda de inspiración, pero también es llamado mirador de “las tres cruces” por alojar las tres cruces que marcan el final del viacrucis que parte desde el pueblito boyacense en semana santa. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/f9kkMgn/1724813098862.jpg", "https://i.ibb.co/rkzvGDz/DSC05968.jpg", "https://i.ibb.co/GVSs3JF/1724813098825.jpg", "https://i.ibb.co/TbhLzj4/1724813098789.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.011723502095549, 5.822148664425425 ] } },
{ "type": "Feature", "properties": { "fid": 7, "nombre": "Mina piedra caliza", "descrip": "Consternarte paisaje antrópico de despojo y extractivismo violento realizado por sucesivas décadas de explotación a cielo abierto de piedra caliza.", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/bbGmF3H/DSC06061.jpg", "https://i.ibb.co/4N4VTDQ/DSC06062.jpg", "https://i.ibb.co/Sn5CcWH/DSC06063.jpg", "https://i.ibb.co/GsgjJ1J/DSC06066.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.001022636456142, 5.826049210333174 ] } },
{ "type": "Feature", "properties": { "fid": 8, "nombre": "Camino peregrinación Tobasía", "descrip": "Cruce de dos caminos diferentes, uno proveniente de Tocogua hacia Tobasía y otro proveniente de la vereda San Luis que se une al primero en este punto. Coincide con la tradicional ruta de los promeseros, o peregrinos a la virgen del Amparo de Tobasía. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/FsS7y7s/DSC05974.jpg", "https://i.ibb.co/9WC32NH/DSC06013.jpg", "https://i.ibb.co/rk1rHL1/DSC06018.jpg", "https://i.ibb.co/QXc7R4V/DSC06090.jpg", "https://i.ibb.co/0Y7yQnC/DSC06091.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.00950570000002, 5.8248885 ] } },
{ "type": "Feature", "properties": { "fid": 10, "nombre": "La piedra de los dos caminos", "descrip": "Es un cruce de caminos despejado y plano, que evoca la existencia de un enorme monolito de piedra caliza que fue explotado y retirado del lugar, pero que en algún momento separó los caminos que subían hacia los actuales abrigos rocosos siguiendo el camino de las manas a la izquierda, y hacia Tobasía por la derecha. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/Npt5TCB/Explanada-de-la-piedra-de-los-dos-caminos.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.006666, 5.822566 ] } },
{ "type": "Feature", "properties": { "fid": 11, "nombre": "Camino de los estudiantes a la escuela", "descrip": "Se trata de un atajo entre el camino Raizal de Tocogua hacia el centro poblado de la vereda y su antigua escuela, actualmente está abandonado y se encuentra cubierto de yerba, sin embargo los habitantes de las partes altas cercanas al hoyo de la calera lo recuerdan con nostalgia por haber representado un significativo ahorro de tiempo en sus tiempos escolares. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/Y0PKhdW/camino-de-los-estudiantes.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.007984, 5.821408 ] } },
{ "type": "Feature", "properties": { "fid": 12, "nombre": "Casa de Piedra", "descrip": "Las huellas de una inmensa casa de piedra al borde del camino Raizal de Tocogua, en medio de un predio encerrado por más de un kilómetro de cerca hecha en piedra rememoran la pujanza de haciendas que antaño destinaban parte de su terreno a ser hosterías para los frecuentes viajeros. ", "modelo_3d": "Sin modelo", "fotografia": [ "https://i.ibb.co/tKgrhMW/DSC06024.jpg", "https://i.ibb.co/3cSFT6X/DSC06026.jpg", "https://i.ibb.co/ZSmDvPp/DSC06028.jpg" ] }, "geometry": { "type": "Point", "coordinates": [ -73.006810359135585, 5.825177086187031 ] } },
{ "type": "Feature", "properties": { "fid": 13, "nombre": "Mural de la identidad Tocoguana", "descrip": "Fin del recorrido. Socialización del mural y conversatorio abierto entorno a la apropiación social del patrimonio.", "modelo_3d": "Sin modelo", "fotografia": "Sin fotografía" }, "geometry": { "type": "Point", "coordinates": [ -73.01115841953856, 5.818323247922247 ] } },
{ "type": "Feature", "properties": { "fid": 14, "nombre": "Pueblito Boyacense", "descrip": "Bienvenida y presentación de la actividad.", "modelo_3d": "Sin modelo", "fotografia": "Sin fotografía" }, "geometry": { "type": "Point", "coordinates": [ -73.018769649838049, 5.825131899689073 ] } }
]
}
